abbr -a l "eza --icons"
abbr -a ll "eza -l --icons --git --group-directories-first --header"
abbr -a la "eza -la --icons --git --group-directories-first --header"
abbr -a lt "eza --tree --icons --git"
abbr -a lt2 "eza --tree --level=2 --icons --git"
abbr -a lg "eza -l --git --icons"
abbr -a ls "eza -lh --icons --git"
abbr -a lx "eza -la --icons --git --group-directories-first --header --time-style=long-iso"
abbr -a lf "eza --icons | fzf"
