# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/c98i343dczj8gyf2xv3r7czn0lj9yra2-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- btop 'btop --force-utf'
    abbr --add -- ffetch fastfetch
    abbr --add -- gco 'git checkout'
    abbr --add -- lg lazygit
    abbr --add -- npu nix-prefetch-url
    abbr --add -- ns 'tv nix-search-tv'

    # Aliases
    alias eza 'eza --icons auto --color auto --git --group-directories-first --header --git-repos --group'
    alias fd 'fd --hidden'
    alias la 'eza -a'
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'

    # Interactive shell initialisation
    /nix/store/6a4wknif1z62kdn3cbkak78kyf462cxj-fzf-0.65.1/bin/fzf --fish | source

    source /nix/store/yl46ir0lmkg6g1mxqd1iw1wl36340adw-base16-gruvbox-material-dark-hard.fish

    # See https://github.com/tomyun/base16-fish/issues/7 for why this condition exists
    if status --is-interactive && test -z "$TMUX"
        base16-gruvbox-material-dark-hard
    end

    set fish_greeting
    set -g fish_key_bindings fish_vi_key_bindings

    /nix/store/wy0ki878xml2dvghl61xr0d3pi07xch1-zoxide-0.9.8/bin/zoxide init fish --cmd cd | source

    /nix/store/7llnlxgizb0d3z8vvdy99m9kycn00vs7-television-0.13.2/bin/tv init fish | source

    if test "$TERM" != dumb
        /nix/store/6hq21mqkmdm1ds9974w9xw00blym6fh5-starship-1.23.0/bin/starship init fish | source
        enable_transience
    end

    function __fish_command_not_found_handler --on-event fish_command_not_found
        /nix/store/4yicfq9kw9n1llc6aq536gnf30zy2yi5-command-not-found $argv
    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION "no-rc enabled"
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/krish/.local/share/fish/home-manager_generated_completions" $post
    end

end
