# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/39e4178d-ed89-47de-bedc-193e9138219d";
    fsType = "btrfs";
    options = ["subvol=@root" "noatime" "ssd" "compress=zstd" "space_cache=v2"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/39e4178d-ed89-47de-bedc-193e9138219d";
    fsType = "btrfs";
    options = ["subvol=@home" "noatime" "compress=zstd" "ssd" "space_cache=v2"];
  };

  fileSystems."/var" = {
    device = "/dev/disk/by-uuid/39e4178d-ed89-47de-bedc-193e9138219d";
    fsType = "btrfs";
    options = ["subvol=@var" "noatime" "compress=zstd" "ssd" "space_cache=v2"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/39e4178d-ed89-47de-bedc-193e9138219d";
    fsType = "btrfs";
    options = ["subvol=@nix" "noatime" "compress=zstd" "ssd" "space_cache=v2"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/39e4178d-ed89-47de-bedc-193e9138219d";
    fsType = "btrfs";
    options = ["noatime" "subvol=swap"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [{device = "/swap/swapfile";}];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
