# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  zoxide = {
    pname = "zoxide";
    version = "e50fd35db5c05e750a74c8f54761922464c1ad5f";
    src = fetchFromGitHub {
      owner = "sayanarijit";
      repo = "zoxide.xplr";
      rev = "e50fd35db5c05e750a74c8f54761922464c1ad5f";
      fetchSubmodules = false;
      sha256 = "sha256-ZiOupn9Vq/czXI3JHvXUlAvAFdXrwoO3NqjjiCZXRnY=";
    };
    date = "2023-01-11";
  };
}
