# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c977906b-f48e-46a4-9340-24642242b47c";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "autodefrag"
      "discard=async"
      "noatime"
      "ssd"
      "space_cache=v2"
      "compress=zstd"
    ];
  };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/34565279-727f-4bca-831d-53c9abe97312";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c977906b-f48e-46a4-9340-24642242b47c";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "autodefrag"
      "discard=async"
      "noatime"
      "ssd"
      "space_cache=v2"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/c977906b-f48e-46a4-9340-24642242b47c";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "autodefrag"
      "discard=async"
      "noatime"
      "ssd"
      "space_cache=v2"
      "compress=zstd"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c977906b-f48e-46a4-9340-24642242b47c";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "autodefrag"
      "discard=async"
      "noatime"
      "ssd"
      "space_cache=v2"
      "compress=zstd"
    ];
  };

  fileSystems."/efi" = {
    device = "/dev/disk/by-uuid/D0A4-2E78";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
