[log]
enabled = true

[mgr]
linemode = "size_and_mtime"
ratio = [1, 4, 3]
show_hidden = true
show_symlink = true
sort_by = "natural"
sort_dir_first = true
sort_reverse = false
sort_sensitive = true

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[plugin.prepend_preloaders]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_preloaders]]
mime = "application/subrip"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "{audio,video,image}/*"
run = "mediainfo"

[[plugin.prepend_previewers]]
mime = "application/subrip"
run = "mediainfo"

[[plugin.prepend_previewers]]
name = "*/"
run = "eza-preview"

[[plugin.prepend_previewers]]
name = "*.csv"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.md"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.rst"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.ipynb"
run = "rich-preview"

[[plugin.prepend_previewers]]
name = "*.json"
run = "rich-preview"

[preview]
cache_dir = ""
image_filter = "lanczos3"
image_quality = 90
max_height = 900
max_width = 600
tab_size = 1
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1

[tasks]
bizarre_retry = 5
macro_workers = 10
micro_workers = 5
